[Variables]

;visit www.weather.codes to find a code for your location. 

Location=USFL0526

;en_GB for metric, en_US for imperial. You can add your own language (for example fr_FR for French, or ja_JP for Japanese) but I cannot guarantee that it will look good

Language=en_US

; Opacity of the black background, between 0 and 255 (default : 192)

BackgroundOpacity=100

;You can set the color of the accents to be Dynamic (meaning it will use Chameleon to pick a color from your wallpaper) or Static (which will use the color you chose below)
;255, 206, 115
;255, 107, 122 

AccentColor=Static
StaticAccentColor=255, 206, 115

;The time (in minutes) between each update. By default the skin connects to weather.com every minute.

UpdateEvery=10

;scale the skin. Defualt is 1. *WARNING* If you scale the skin tool large it may crash rainmeter.
;If this happens and rainmeter continues to crash open userSetting.inc from file explorer in your rainmeter/skins/lottaweather/@Resources folder and lower the scale

scale=0.85